package com.mdebysmn.assistant;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.net.Uri; import android.view.*; import android.view.inputmethod.InputMethodManager; import android.widget.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.util.concurrent.*; import org.json.*;

public class MainActivity extends Activity {
  LinearLayout messages; EditText input; TextView status; SharedPreferences prefs; ExecutorService exec=Executors.newSingleThreadExecutor();
  int purple=Color.rgb(139,92,246);
  @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("mde_ai",0); build();}
  TextView tv(String s,float sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.WHITE);t.setPadding(20,16,20,16);return t;}
  void build(){
    LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(11,11,16));
    LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(12,8,8,8);
    TextView logo=tv("MDE",20);logo.setTextColor(purple);bar.addView(logo,new LinearLayout.LayoutParams(60,60));
    TextView title=tv("MDE AI Assistant",18);bar.addView(title,new LinearLayout.LayoutParams(0,60,1));
    Button settings=new Button(this);settings.setText("⚙");settings.setOnClickListener(v->settings());bar.addView(settings,new LinearLayout.LayoutParams(60,60));root.addView(bar);
    status=tv("Ready • Configure an AI endpoint in Settings",12);status.setTextColor(Color.LTGRAY);root.addView(status);
    ScrollView scroll=new ScrollView(this);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(8,8,8,8);scroll.addView(messages);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    LinearLayout composer=new LinearLayout(this);composer.setPadding(8,8,8,12);
    input=new EditText(this);input.setHint("Ask anything…");input.setTextColor(Color.WHITE);input.setHintTextColor(Color.GRAY);input.setBackgroundColor(Color.rgb(30,30,38));input.setPadding(18,10,18,10);composer.addView(input,new LinearLayout.LayoutParams(0,60,1));
    Button send=new Button(this);send.setText("Send");send.setOnClickListener(v->send());composer.addView(send,new LinearLayout.LayoutParams(90,60));root.addView(composer);
    setContentView(root); addMessage("assistant","MDE AI is ready. Set an OpenAI-compatible endpoint and model in Settings, then send a message."); }
  void addMessage(String who,String text){TextView m=tv((who.equals("user")?"You\n":"MDE AI\n")+text,15);m.setBackgroundColor(who.equals("user")?Color.rgb(40,32,55):Color.rgb(23,23,30));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(4,6,4,6);messages.addView(m,p);}
  void send(){String q=input.getText().toString().trim();if(q.isEmpty())return;String endpoint=prefs.getString("endpoint","");String model=prefs.getString("model","Qwen/Qwen3.5-4B-Instruct");String key=prefs.getString("key","");if(endpoint.isEmpty()){settings();Toast.makeText(this,"Configure the AI endpoint first",Toast.LENGTH_LONG).show();return;}addMessage("user",q);input.setText("");status.setText("Generating…");exec.submit(()->{try{JSONObject body=new JSONObject();body.put("model",model);body.put("stream",false);JSONArray a=new JSONArray();JSONObject sys=new JSONObject();sys.put("role","system");sys.put("content",prefs.getString("system","You are MDE AI, a helpful general-purpose assistant. Be direct and factual."));a.put(sys);JSONObject u=new JSONObject();u.put("role","user");u.put("content",q);a.put(u);body.put("messages",a);HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");if(!key.isEmpty())c.setRequestProperty("Authorization","Bearer "+key);try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}int code=c.getResponseCode();InputStream is=code>=400?c.getErrorStream():c.getInputStream();String out=read(is);if(code>=400)throw new Exception("HTTP "+code+": "+out);JSONObject r=new JSONObject(out);String ans="";if(r.has("choices"))ans=r.getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content","");else ans=r.optString("response",out);final String f=ans;runOnUiThread(()->{addMessage("assistant",f);status.setText("Ready");});}catch(Exception e){runOnUiThread(()->{addMessage("assistant","Error: "+e.getMessage());status.setText("Connection error");});}});}
  String read(InputStream is)throws Exception{if(is==null)return "";BufferedReader br=new BufferedReader(new InputStreamReader(is,StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=br.readLine())!=null)s.append(l);return s.toString();}
  void settings(){LinearLayout l=new LinearLayout(this);l.setPadding(30,10,30,10);l.setOrientation(LinearLayout.VERTICAL);EditText ep=field("OpenAI-compatible endpoint",prefs.getString("endpoint",""));EditText mo=field("Model",prefs.getString("model","Qwen/Qwen3.5-4B-Instruct"));EditText key=field("API token (optional)",prefs.getString("key",""));EditText sy=field("System instructions",prefs.getString("system","You are MDE AI, a helpful general-purpose assistant. Be direct and factual."));l.addView(ep);l.addView(mo);l.addView(key);l.addView(sy);new AlertDialog.Builder(this).setTitle("MDE AI Settings").setView(l).setPositiveButton("Save",(d,w)->{prefs.edit().putString("endpoint",ep.getText().toString().trim()).putString("model",mo.getText().toString().trim()).putString("key",key.getText().toString().trim()).putString("system",sy.getText().toString()).apply();status.setText("Settings saved");}).setNegativeButton("Cancel",null).show();}
  EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value);e.setPadding(8,16,8,16);return e;}
  @Override protected void onDestroy(){exec.shutdownNow();super.onDestroy();}
}
